export const info =[
    {
        "id": 1,
        "valueResponse": " ¡Hola! Soy Bicenta, tu asistente virtual del Banco Bicentenario. Estoy aquí para ayudarte en el uso de nuestras soluciones y plataformas digitales. Estos son algunos de los temas más consultados por nuestros clientes. ¿En qué puedo ayudarte hoy?&Consultas y tarjetas de débito.&Errores en nuestra plataforma&Paso a paso de operaciones frecuentes. &Otros canales de atención&POS (Puntos de Venta)&Créditos y tarjetas de credito&Productos",
        "priority": "LOW",
        "multimedia": null,
        "multimediaContentType": "image/png",
        "multimediaVoice": null,
        "multimediaVoiceContentType": "audio/mpeg",
        "saraAnimation": null,
        "saraAnimationContentType": "image/gif",
        "isEndConversation": false,
        "responseType": "QUERY",
        "url": null,
        "multimediaUrl": "https://bankbot.zaccoapp.com:2626/img4/1707414936686img.png",
        "multimediaVoiceUrl": "https://bankbot.zaccoapp.com:2626/img4/1707505085327m.mp3",
        "saraAnimationUrl": "https://bankbot.zaccoapp.com:2626/img4/1707414936689a.gif",
        "multimediaType": "VISUAL",
        "showMultimedia": true,
        "multimediaVideo": null,
        "multimediaVideoContentType": "video/mp4",
        "multimediaVideoUrl": "https://bankbot.zaccoapp.com:2626/img4/1708270082573v.mp4",
        "multimediaVideoPath": "/home/ubuntu/plataform/ImageChatbot/1708270082573v.mp4",
        "intents": [
            {
                "id": 1,
                "intenType": "INFO",
                "name": "hola",
                "description": "hola",
                "urlRequest": "hola",
                "enabled": false,
                "creationDate": "2024-02-08T17:57:00Z"
            },
            {
                "id": 4,
                "intenType": "INFO",
                "name": "Me gustan las arepas",
                "description": "Me gustan las arepas",
                "urlRequest": "Me gustan las arepas",
                "enabled": true,
                "creationDate": "2024-05-07T13:55:00Z"
            }
        ],
        "channelMultimedias": null,
        "channelVoices": null,
        "channelAnimations": null
    },
    {
        "id": 2,
        "valueResponse": "Entiendo que puedas tener frustraciones o preocupaciones, pero te pido que mantengamos una comunicación respetuosa. Estoy aquí para ayudarte con cualquier pregunta o problema que tengas relacionado con nuestros servicios bancarios. ",
        "priority": "LOW",
        "multimedia": null,
        "multimediaContentType": null,
        "multimediaVoice": null,
        "multimediaVoiceContentType": null,
        "saraAnimation": null,
        "saraAnimationContentType": null,
        "isEndConversation": false,
        "responseType": "QUERY",
        "url": null,
        "multimediaUrl": null,
        "multimediaVoiceUrl": null,
        "saraAnimationUrl": null,
        "multimediaType": "VISUAL",
        "showMultimedia": false,
        "multimediaVideo": null,
        "multimediaVideoContentType": "video/mp4",
        "multimediaVideoUrl": "https://bankbot.zaccoapp.com:2626/img4/1708271545310v.mp4",
        "multimediaVideoPath": "/home/ubuntu/plataform/ImageChatbot/1708271545310v.mp4",
        "intents": [
            {
                "id": 2,
                "intenType": "INFO",
                "name": "groseria",
                "description": "groseria",
                "urlRequest": "groseria",
                "enabled": false,
                "creationDate": "2024-02-18T15:52:00Z"
            },
            {
                "id": 4,
                "intenType": "INFO",
                "name": "Me gustan las arepas",
                "description": "Me gustan las arepas",
                "urlRequest": "Me gustan las arepas",
                "enabled": true,
                "creationDate": "2024-05-07T13:55:00Z"
            }
        ],
        "channelMultimedias": null,
        "channelVoices": null,
        "channelAnimations": null
    },
    {
        "id": 3,
        "valueResponse": "Soy una mujer venezolana de 25 años, producto de la mezcla de las culturas que caracterizan a nuestro país (Indígena de la Guajira con Yanomami + negro afrodescendiente + español), de piel color canela, labios gruesos, cabello liso largo negro, ojos marrones. soy una muchacha preparada, profesional y luchadora con deseos de crecer, dispuesta siempre a brindar apoyo y servir con educación y convicción a las personas. ",
        "priority": "LOW",
        "multimedia": null,
        "multimediaContentType": null,
        "multimediaVoice": null,
        "multimediaVoiceContentType": null,
        "saraAnimation": null,
        "saraAnimationContentType": null,
        "isEndConversation": false,
        "responseType": "QUERY",
        "url": null,
        "multimediaUrl": null,
        "multimediaVoiceUrl": null,
        "saraAnimationUrl": null,
        "multimediaType": "VISUAL",
        "showMultimedia": false,
        "multimediaVideo": null,
        "multimediaVideoContentType": "video/mp4",
        "multimediaVideoUrl": "https://bankbot.zaccoapp.com:2626/img4/1708273129175v.mp4",
        "multimediaVideoPath": "/home/ubuntu/plataform/ImageChatbot/1708273129175v.mp4",
        "intents": [
            {
                "id": 3,
                "intenType": "INFO",
                "name": "Quien es bicenta",
                "description": "Quien es bicenta",
                "urlRequest": "Quien es bicenta",
                "enabled": false,
                "creationDate": "2024-02-18T16:19:00Z"
            }
        ],
        "channelMultimedias": null,
        "channelVoices": null,
        "channelAnimations": null
    },
    {
        "id": 4,
        "valueResponse": "a mi tambien me gustan las arepas",
        "priority": "LOW",
        "multimedia": null,
        "multimediaContentType": null,
        "multimediaVoice": null,
        "multimediaVoiceContentType": null,
        "saraAnimation": null,
        "saraAnimationContentType": null,
        "isEndConversation": false,
        "responseType": "QUERY",
        "url": null,
        "multimediaUrl": null,
        "multimediaVoiceUrl": null,
        "saraAnimationUrl": null,
        "multimediaType": "VISUAL",
        "showMultimedia": false,
        "multimediaVideo": null,
        "multimediaVideoContentType": null,
        "multimediaVideoUrl": null,
        "multimediaVideoPath": null,
        "intents": [],
        "channelMultimedias": null,
        "channelVoices": null,
        "channelAnimations": null
    }
]